from tkinter import *
import time
def data():
    ttime=time.strftime('%r')
    dateformate=time.strftime("%a,%d %h %Y")
    standard_date=time.strftime("%d/%m/%y")
    no_week=time.strftime("Week No : %W")
    labs.config(text=standard_date)
    labe.config(text=ttime)
    labh.config(text=dateformate)
    lab_week.config(text=no_week)
    labs.after(200,data)
clock=Tk()
clock.title(' anush calendar ')
clock.geometry("500x300")
clock.config(bg="purple")
labh=Label(clock,font=("Palatino",40,"italic"),bg="purple",fg='yellow')
labh.pack()
labs=Label(clock,font=("palatino",40,"italic"),bg='purple',fg='yellow')
labs.pack()
labe=Label(clock,font=("palatino",40,"italic"),bg='purple',fg='yellow')
labe.pack()
lab_week=Label(clock,font=("palatino",40),bg='purple',fg='yellow')
lab_week.pack()
data()
clock.mainloop()